-- Create promo_codes table
create table if not exists promo_codes (
  id bigint generated by default as identity primary key,
  code text not null unique,
  discount_type text not null check (discount_type in ('percent', 'fixed')),
  value numeric not null,
  partner_name text,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table promo_codes enable row level security;

-- Allow public read access to promo_codes (so users can check them)
create policy "Allow public read access to promo_codes"
  on promo_codes for select
  using (true);

-- Insert sample data (optional, can be removed)
insert into promo_codes (code, discount_type, value, partner_name) values
('BLOGGER10', 'percent', 10, 'Blogger One'),
('SUMMER500', 'fixed', 500, 'Summer Campaign'),
('PROMO10', 'percent', 10, 'Legacy Code'),
('PROMO200', 'fixed', 200, 'Legacy Code')
on conflict (code) do nothing;
