-- Contest Tables

-- 1. Participants
-- Stores user info and their contest state
create table if not exists contest_participants (
  user_id bigint primary key, -- Telegram ID
  first_name text,
  username text,
  tickets integer default 0,
  personal_promo_code text unique,
  referrer_id bigint references contest_participants(user_id),
  created_at timestamptz default now()
);

-- 2. Referrals (Subscriptions)
-- Tracks who invited whom for the "Subscription" method
create table if not exists contest_referrals (
  id bigint generated by default as identity primary key,
  referrer_id bigint references contest_participants(user_id),
  referee_id bigint references contest_participants(user_id),
  status text default 'joined', -- 'joined'
  created_at timestamptz default now(),
  unique(referrer_id, referee_id)
);

-- 3. Tickets Log
-- History of all ticket transactions
create table if not exists contest_tickets_log (
  id bigint generated by default as identity primary key,
  user_id bigint references contest_participants(user_id),
  amount integer,
  reason text, -- 'purchase_1000', 'referral_milestone_3', 'referral_milestone_5', 'referral_milestone_10', 'friend_purchase_promo', 'ugc_reward'
  related_id text, -- order_id or other reference
  created_at timestamptz default now()
);

-- RLS Policies (Enable RLS for security)
alter table contest_participants enable row level security;
alter table contest_referrals enable row level security;
alter table contest_tickets_log enable row level security;

-- Allow public read access (for leaderboard/stats if needed) or restricted to user
create policy "Users can read their own data" on contest_participants
  for select using (auth.uid()::text = user_id::text);

-- Allow service role full access (we will use service role in API/Bot)
-- (Note: By default service role bypasses RLS, so this is for client access if any)

