-- Скопируйте этот код в SQL Editor в панели управления Supabase (https://supabase.com/dashboard/project/meibdfguaaqcprvyfrpr/sql)
-- и нажмите "Run".

create table if not exists test_connection (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  message text
);

-- Разрешаем доступ всем (для теста)
alter table test_connection enable row level security;

create policy "Enable read access for all users"
on test_connection for select
using (true);

create policy "Enable insert access for all users"
on test_connection for insert
with check (true);

insert into test_connection (message) values ('Таблица успешно создана!');
