-- Create table for contest participants
create table if not exists contest_participants (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id text, -- Unique identifier of the participant (e.g., Telegram ID or Email)
  ticket_numbers text[], -- Array of ticket numbers assigned to the participant
  status text default 'active', -- Status of participation (active, disqualified, winner, etc.)
  contact_info jsonb -- Optional: Store contact info like name, phone, email
);

-- Enable Row Level Security (RLS)
alter table contest_participants enable row level security;

-- Create policy to allow read access for everyone (or restrict as needed)
create policy "Enable read access for all users" on contest_participants
  for select using (true);

-- Create policy to allow insert for service role (or authenticated users)
create policy "Enable insert for service role only" on contest_participants
  for insert with check (true);
