create table if not exists bot_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now(),
  type text,
  message text,
  data jsonb
);

alter table bot_logs enable row level security;

create policy "Enable insert for service role only" on bot_logs
  for insert with check (true);

create policy "Enable select for service role only" on bot_logs
  for select using (true);
