-- 1. Add updated_at column
alter table orders 
add column if not exists updated_at timestamp with time zone default now();

-- 2. Make ID auto-increment (Identity)
-- We wrap in a DO block to avoid errors if already done
do $$
begin
  alter table orders alter column id add generated by default as identity;
exception when others then
  -- ignore error if column is already identity or other issues
  raise notice 'Could not make id identity (maybe already is?): %', SQLERRM;
end;
$$;

-- 3. Sync the sequence to the max ID (in case there are existing rows)
select setval(pg_get_serial_sequence('orders', 'id'), coalesce(max(id), 0) + 1, false) from orders;
