
-- Fix products id to be auto-incrementing
BEGIN;

-- First, ensure id is not just a default value but an identity
-- We might need to drop existing default if any
ALTER TABLE products ALTER COLUMN id DROP DEFAULT;

-- Change to identity column
ALTER TABLE products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Sync the sequence to the max id
SELECT setval(pg_get_serial_sequence('products', 'id'), COALESCE((SELECT MAX(id) FROM products), 0) + 1, false);

COMMIT;
