import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SnowfallBackground } from "@/components/ui/snow-flakes";
import Garland from "@/components/ui/garland";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Garland />
        {children}
        <div className="fixed inset-0 pointer-events-none z-50">
          <SnowfallBackground count={120} speed={0.6} minSize={2} maxSize={14} minOpacity={0.2} maxOpacity={0.9} color="#9dd4ff" zIndex={1} wind={true} />
        </div>
      </body>
    </html>
  );
}
